# Permite definir y ejecutar varios contenedores al mismo tiempo.

version: "3.8"

services:
  # Este servicio construye la imagen de la API usando el Dockerfile.
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/usersdb
    # Indica que la API depende del servicio MongoDB.
    depends_on:
      - mongo

  mongo:
    # Este servicio utiliza la imagen oficial de MongoDB.
    image: mongo:7
    ports:
      - "27017:27017"
    # Define un volumen para que los datos de MongoDB sean persistentes.
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: